name: oasis_statistic_server
description: Dart gRPC game statistic server
version: 1.0.0
# repository: https://github.com/my_org/my_repo

environment:
  sdk: ^3.0.0

# Add regular dependencies here.
dependencies:
  intl: ^0.18.1
  #gRPC
  grpc: ^3.2.3
  protobuf: ^3.1.0
  #crypto
  pointycastle: ^3.7.3
  basic_utils: ^5.6.1 # read private key DER file

  #other
  freezed: ^2.4.1
  freezed_annotation: ^2.4.1
  json_annotation: ^4.8.0
  collection: ^1.18.0

  #drift
  drift: ^2.11.0


  path: ^1.8.3

dev_dependencies:
  lints: ^2.1.1
  test: ^1.24.6
  build_runner: ^2.4.6
  #drift dev
  drift_dev: ^2.11.0
  json_serializable: ^6.7.1
