name: oasis_statistic_server
description: A sample command-line application.
version: 1.0.0
# repository: https://github.com/my_org/my_repo

environment:
  sdk: ^3.0.0

# Add regular dependencies here.
dependencies:
  intl: ^0.18.1
  #gRPC
  grpc: ^3.2.3
  protobuf: ^3.1.0
  #crypto
  #cryptography: ^2.5.0
  pointycastle: ^3.7.3
  basic_utils: ^5.6.1
  crypto: ^3.0.3
  convert: ^3.1.1
  bs58: ^1.0.2
  collection: ^1.18.0

  #other
  freezed: ^2.4.2
  freezed_annotation: ^2.4.1

dev_dependencies:
  lints: ^2.1.1
  test: ^1.24.6
  build_runner: ^2.4.6
